### ISSUE TITLE
NullException?

### ISSUE THREAD

**Issue by dsrdakota** [EvaisaDev/UnityNetcodePatcher#37]
I am having issues running this specific command:
netcode-patch --no-overwrite ".\Template\bin\Template.dll" "deps"
[21:11:29 INF] Initializing NetcodePatcher v4.2.0+ad7150341ed4871f094b22bfb99ad0c831995bc1
[21:11:29 DBG] Provided 'plugins' input: .\Template\bin\Template.dll
[21:11:29 DBG] Provided 'dependencies' input: ["deps"]
[21:11:29 INF] Patching 1 assemblies:
["Template.dll"]
[21:11:29 INF] Found 151 dependency assemblies:
["AmazingAssets.TerrainToMesh.dll", "Assembly-CSharp-firstpass.dll", "Assembly-CSharp.dll", "ClientNetworkTransform.dll", "DissonanceVoip.dll", "Facepunch Transport for Netcode for GameObjects.dll", "Facepunch.Steamworks.Win64.dll", "Mono.Security.dll", "mscorlib.dll", "netstandard.dll", "Newtonsoft.Json.dll", "System.ComponentModel.Composition.dll", "System.Configuration.dll", "System.Core.dll", "System.Data.DataSetExtensions.dll", "System.Data.dll", "System.dll", "System.Drawing.dll", "System.EnterpriseServices.dll", "System.IO.Compression.dll", "System.IO.Compression.FileSystem.dll", "System.Net.Http.dll", "System.Numerics.dll", "System.Runtime.dll", "System.Runtime.Serialization.dll", "System.Security.dll", "System.ServiceModel.Internals.dll", "System.Transactions.dll", "System.Xml.dll", "System.Xml.Linq.dll", "Unity.AI.Navigation.dll", "Unity.Animation.Rigging.dll", "Unity.Animation.Rigging.DocCodeExamples.dll", "Unity.Burst.dll", "Unity.Burst.Unsafe.dll", "Unity.Collections.dll", "Unity.Collections.LowLevel.ILSupport.dll", "Unity.InputSystem.dll", "Unity.InputSystem.ForUI.dll", "Unity.Jobs.dll", "Unity.Mathematics.dll", "Unity.Multiplayer.Tools.Common.dll", "Unity.Multiplayer.Tools.MetricTypes.dll", "Unity.Multiplayer.Tools.NetStats.dll", "Unity.Multiplayer.Tools.NetStatsMonitor.Component.dll", "Unity.Multiplayer.Tools.NetStatsMonitor.Configuration.dll", "Unity.Multiplayer.Tools.NetStatsMonitor.Implementation.dll", "Unity.Multiplayer.Tools.NetStatsReporting.dll", "Unity.Multiplayer.Tools.NetworkProfiler.Runtime.dll", "Unity.Multiplayer.Tools.NetworkSolutionInterface.dll", "Unity.Netcode.Components.dll", "Unity.Netcode.Runtime.dll", "Unity.Networking.Transport.dll", "Unity.ProBuilder.Csg.dll", "Unity.ProBuilder.dll", "Unity.ProBuilder.KdTree.dll", "Unity.ProBuilder.Poly2Tri.dll", "Unity.ProBuilder.Stl.dll", "Unity.Profiling.Core.dll", "Unity.RenderPipelines.Core.Runtime.dll", "Unity.RenderPipelines.Core.ShaderLibrary.dll", "Unity.RenderPipelines.HighDefinition.Config.Runtime.dll", "Unity.RenderPipelines.HighDefinition.Runtime.dll", "Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.dll", "Unity.Services.Authentication.dll", "Unity.Services.Core.Analytics.dll", "Unity.Services.Core.Configuration.dll", "Unity.Services.Core.Device.dll", "Unity.Services.Core.dll", "Unity.Services.Core.Environments.dll", "Unity.Services.Core.Environments.Internal.dll", "Unity.Services.Core.Internal.dll", "Unity.Services.Core.Networking.dll", "Unity.Services.Core.Registration.dll", "Unity.Services.Core.Scheduler.dll", "Unity.Services.Core.Telemetry.dll", "Unity.Services.Core.Threading.dll", "Unity.Services.QoS.dll", "Unity.Services.Relay.dll", "Unity.TextMeshPro.dll", "Unity.Timeline.dll", "Unity.VisualEffectGraph.Runtime.dll", "UnityEngine.AccessibilityModule.dll", "UnityEngine.AIModule.dll", "UnityEngine.AndroidJNIModule.dll", "UnityEngine.AnimationModule.dll", "UnityEngine.ARModule.dll", "UnityEngine.AssetBundleModule.dll", "UnityEngine.AudioModule.dll", "UnityEngine.ClothModule.dll", "UnityEngine.ClusterInputModule.dll", "UnityEngine.ClusterRendererModule.dll", "UnityEngine.ContentLoadModule.dll", "UnityEngine.CoreModule.dll", "UnityEngine.CrashReportingModule.dll", "UnityEngine.DirectorModule.dll", "UnityEngine.dll", "UnityEngine.DSPGraphModule.dll", "UnityEngine.GameCenterModule.dll", "UnityEngine.GIModule.dll", "UnityEngine.GridModule.dll", "UnityEngine.HotReloadModule.dll", "UnityEngine.ImageConversionModule.dll", "UnityEngine.IMGUIModule.dll", "UnityEngine.InputLegacyModule.dll", "UnityEngine.InputModule.dll", "UnityEngine.JSONSerializeModule.dll", "UnityEngine.LocalizationModule.dll", "UnityEngine.NVIDIAModule.dll", "UnityEngine.ParticleSystemModule.dll", "UnityEngine.PerformanceReportingModule.dll", "UnityEngine.Physics2DModule.dll", "UnityEngine.PhysicsModule.dll", "UnityEngine.ProfilerModule.dll", "UnityEngine.PropertiesModule.dll", "UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll", "UnityEngine.ScreenCaptureModule.dll", "UnityEngine.SharedInternalsModule.dll", "UnityEngine.SpriteMaskModule.dll", "UnityEngine.SpriteShapeModule.dll", "UnityEngine.StreamingModule.dll", "UnityEngine.SubstanceModule.dll", "UnityEngine.SubsystemsModule.dll", "UnityEngine.TerrainModule.dll", "UnityEngine.TerrainPhysicsModule.dll", "UnityEngine.TextCoreFontEngineModule.dll", "UnityEngine.TextCoreTextEngineModule.dll", "UnityEngine.TextRenderingModule.dll", "UnityEngine.TilemapModule.dll", "UnityEngine.TLSModule.dll", "UnityEngine.UI.dll", "UnityEngine.UIElementsModule.dll", "UnityEngine.UIModule.dll", "UnityEngine.UmbraModule.dll", "UnityEngine.UnityAnalyticsCommonModule.dll", "UnityEngine.UnityAnalyticsModule.dll", "UnityEngine.UnityConnectModule.dll", "UnityEngine.UnityCurlModule.dll", "UnityEngine.UnityTestProtocolModule.dll", "UnityEngine.UnityWebRequestAssetBundleModule.dll", "UnityEngine.UnityWebRequestAudioModule.dll", "UnityEngine.UnityWebRequestModule.dll", "UnityEngine.UnityWebRequestTextureModule.dll", "UnityEngine.UnityWebRequestWWWModule.dll",
 "UnityEngine.VehiclesModule.dll", "UnityEngine.VFXModule.dll", "UnityEngine.VideoModule.dll", "UnityEngine.VirtualTexturingModule.dll", "UnityEngine.VRModule.dll", "UnityEngine.WindModule.dll", "UnityEngine.XRModule.dll"]
[21:11:29 DBG] Loading patcher from C:\Users\Dakota\.dotnet\tools\.store\evaisa.netcodepatcher.cli\4.2.0\evaisa.netcodepatcher.cli\4.2.0\tools\net8.0\any\unity-v2022.3\unity-transport-v1.0.0\netcode-v1.5.2\without-native-collection-support\NetcodePatcher.dll
[21:11:31 INF] Reading : Template.dll
[21:11:31 INF] Found debug info : (Template.pdb)
[21:11:31 INF] Patching : Template.dll
[21:11:31 ERR] Failed to patch (Template.dll): System.ArgumentNullException: Value cannot be null. (Parameter 'method')
   at Mono.Cecil.Mixin.CheckMethod(Object method)
   at Mono.Cecil.ModuleDefinition.ImportReference(MethodReference method, IGenericParameterProvider context)
   at Mono.Cecil.ModuleDefinition.ImportReference(MethodReference method)
   at NetcodePatcher.CodeGen.ApplyPatchedAttributeILPP.Process(ICompiledAssembly compiledAssembly) in /home/runner/work/UnityNetcodePatcher/UnityNetcodePatcher/NetcodePatcher/NetcodePatcher/CodeGen/ApplyPatchedAttributeILPP.cs:line 80

**Comment by Wild-W** [comment]
I also had this error when using netcode-patch on a net8.0 project. Switching to netstandard2.1 fixed this issue for me.

**Comment by Lordfirespeed** [comment]
netcode-patch should never be used on an assembly targeting net8.0 as Unity's runtime is netstandard2.1-like
