### ISSUE TITLE
System.IO.IOException

### ISSUE THREAD

**Issue by Ccode-lang** [EvaisaDev/UnityNetcodePatcher#38]
When I use the netcode patcher it Throws an IO exception saying my plugin DLL is in use by another process.  

```
1>[08:25:03 DBG] Loading patcher from C:\Users\Cooper Lynn\.dotnet\tools\.store\evaisa.netcodepatcher.cli\4.2.0\evaisa.netcodepatcher.cli\4.2.0\tools\net8.0\any\unity-v2022.3\unity-transport-v1.0.0\netcode-v1.5.2\without-native-collection-support\NetcodePatcher.dll
1>[08:25:05 INF] Reading : LethalSirenHead.dll
1>[08:25:05 INF] Found debug info : (LethalSirenHead.pdb)
1>[08:25:05 INF] Patching : LethalSirenHead.dll
1>[08:25:05 INF] Deleting : LethalSirenHead_original.dll
1>[08:25:05 ERR] Failed to patch (LethalSirenHead.dll): System.IO.IOException: The process cannot access the file because it is being used by another process.
1>   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
1>   at NetcodePatcher.CodeGen.NetcodeILPPApplicator.ApplyProcesses() in /home/runner/work/UnityNetcodePatcher/UnityNetcodePatcher/NetcodePatcher/NetcodePatcher/CodeGen/NetcodeILPPApplicator.cs:line 101
1>   at NetcodePatcher.Patcher.Patch(String assemblyPath, String outputPath, String[] references) in /home/runner/work/UnityNetcodePatcher/UnityNetcodePatcher/NetcodePatcher/NetcodePatcher/Patcher.cs:line 56
1>[08:25:05 FTL] Exception, cannot continue!
1>System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
1> ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
1> ---> System.IO.IOException: The process cannot access the file because it is being used by another process.
1>   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
1>   at NetcodePatcher.CodeGen.NetcodeILPPApplicator.ApplyProcesses() in /home/runner/work/UnityNetcodePatcher/UnityNetcodePatcher/NetcodePatcher/NetcodePatcher/CodeGen/NetcodeILPPApplicator.cs:line 101
1>   at NetcodePatcher.Patcher.Patch(String assemblyPath, String outputPath, String[] references) in /home/runner/work/UnityNetcodePatcher/UnityNetcodePatcher/NetcodePatcher/NetcodePatcher/Patcher.cs:line 56
1>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
1>   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
1>   --- End of inner exception stack trace ---
1>   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
1>   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
1>   at NetcodePatcher.Cli.NetcodePatchCommand.<>c__DisplayClass1_0.<Handle>g__Patch|2(FileInfo pluginAssembly) in /home/runner/work/UnityNetcodePatcher/UnityNetcodePatcher/NetcodePatcher.Cli/NetcodePatchCommand.cs:line 129
1>   at System.Collections.Generic.List`1.ForEach(Action`1 action)
1>   at NetcodePatcher.Cli.NetcodePatchCommand.Handle(FileSystemInfo plugin, FileSystemInfo[] dependencies, String netcodeVersion, String transportVersion, String unityVersion, Boolean nativeCollectionSupport, String output, Boolean noOverwrite, Boolean disableParallel, LogEventLevel minimumLogEventLevel, String logFile) in /home/runner/work/UnityNetcodePatcher/UnityNetcodePatcher/NetcodePatcher.Cli/NetcodePatchCommand.cs:line 134
1>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
1>   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>   --- End of inner exception stack trace ---
1>   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>   at System.Delegate.DynamicInvokeImpl(Object[] args)
1>   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
1>   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
1>C:\Users\Cooper Lynn\source\repos\LeathalSirenHead\LethalSirenHead.csproj(89,5): error MSB3073: The command "netcode-patch "C:\Users\Cooper Lynn\source\repos\LeathalSirenHead\bin\Debug\netcoreapp2.1\LethalSirenHead.dll" "C:\Users\Cooper Lynn\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Default\BepInEx\core\0Harmony.dll" "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Assembly-CSharp-firstpass.dll" "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Assembly-CSharp.dll" "C:\Users\Cooper Lynn\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Default\BepInEx\core\BepInEx.dll" "C:\Users\Cooper Lynn\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Default\BepInEx\plugins\Evaisa-LethalLib\LethalLib\LethalLib.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\Microsoft.CSharp.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\Microsoft.VisualBasic.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\Microsoft.Win32.Primitives.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\mscorlib.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\netstandard.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.AppContext.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Buffers.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Collections.Concurrent.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Collections.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Collections.Immutable.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Collections.NonGeneric.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Collections.Specialized.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.ComponentModel.Annotations.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.ComponentModel.DataAnnotations.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.ComponentModel.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.ComponentModel.EventBasedAsync.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.ComponentModel.Primitives.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.ComponentModel.TypeConverter.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Configuration.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Console.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Core.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Data.Common.dll" "C:\Users\Cooper Lynn\.nuget\packages\system.data.datasetextensions\4.5.0\ref\netstandard2.0\System.Data.DataSetExtensions.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Data.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Diagnostics.Contracts.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Diagnostics.Debug.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Diagnostics.DiagnosticSource.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Diagnostics.FileVersionInfo.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Diagnostics.Process.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Diagnostics.StackTrace.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Diagnostics.TextWriterTraceListener.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Diagnostics.Tools.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Diagnostics.TraceSource.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Diagnostics.Tracing.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Drawing.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Drawing.Primitives.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Dynamic.Runtime.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Globalization.Calendars.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Globalization.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Globalization.Extensions.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.Compression.Brotli.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.Compression.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.Compression.FileSystem.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.Compression.ZipFile.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.FileSystem.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.FileSystem.DriveInfo.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.FileSystem.Primitives.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.FileSystem.Watcher.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.IsolatedStorage.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.MemoryMappedFiles.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.Pipes.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.IO.UnmanagedMemoryStream.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Linq.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Linq.Expressions.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Linq.Parallel.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Linq.Queryable.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Memory.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.Http.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.HttpListener.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.Mail.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.NameResolution.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.NetworkInformation.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.Ping.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.Primitives.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.Requests.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.Security.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.ServicePoint.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.Sockets.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.WebClient.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.WebHeaderCollection.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.WebProxy.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.WebSockets.Client.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Net.WebSockets.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Numerics.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Numerics.Vectors.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.ObjectModel.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Reflection.DispatchProxy.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Reflection.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Reflection.Emit.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Reflection.Emit.ILGeneration.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Reflection.Emit.Lightweight.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Reflection.Extensions.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Reflection.Metadata.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Reflection.Primitives.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Reflection.TypeExtensions.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Resources.Reader.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Resources.ResourceManager.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Resources.Writer.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.CompilerServices.VisualC.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.Extensions.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.Handles.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.InteropServices.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.InteropServices.RuntimeInformation.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.InteropServices.WindowsRuntime.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.Loader.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.Numerics.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.Serialization.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.Serialization.Formatters.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.Serialization.Json.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.Serialization.Primitives.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.Serialization.Xml.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Security.Claims.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Security.Cryptography.Algorithms.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Security.Cryptography.Csp.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Security.Cryptography.Encoding.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Security.Cryptography.Primitives.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Security.Cryptography.X509Certificates.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Security.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Security.Principal.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Security.SecureString.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.ServiceModel.Web.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.ServiceProcess.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Text.Encoding.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Text.Encoding.Extensions.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Text.RegularExpressions.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Threading.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Threading.Overlapped.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Threading.Tasks.Dataflow.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Threading.Tasks.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Threading.Tasks.Extensions.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Threading.Tasks.Parallel.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Threading.Thread.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Threading.ThreadPool.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Threading.Timer.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Transactions.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Transactions.Local.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.ValueTuple.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Web.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Web.HttpUtility.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Windows.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Xml.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Xml.Linq.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Xml.ReaderWriter.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Xml.Serialization.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Xml.XDocument.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Xml.XmlDocument.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Xml.XmlSerializer.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Xml.XPath.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Xml.XPath.XDocument.dll" "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Unity.Netcode.Runtime.dll" "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.AIModule.dll" "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.AnimationModule.dll" "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.AssetBundleModule.dll" "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.AudioModule.dll" "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.CoreModule.dll" "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.dll" "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.PhysicsModule.dll" "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.UI.dll" "C:\Users\Cooper Lynn\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\WindowsBase.dll"" exited with code -1.
1>Done building project "LethalSirenHead.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 8:25 AM and took 04.297 seconds ==========
```

**Comment by Ccode-lang** [comment]
I have tried updating now and it doesn't work still

**Comment by Wexop** [comment]
Hello !
I got the same issue, do you remember how you fixed this ?

**Comment by Ccode-lang** [comment]
I don't remember. I remember doing something wrong with the project file. I might even have restarted my computer just to see if that would fix it.

**Comment by Wexop** [comment]
I fixed it !

I needed to add        ` <DebugType>embedded</DebugType>` in <PropertyGroup>
